<?php
namespace App\Controller;

use App\Service\Utility;
use Cake\Event\EventInterface;

class CoreController extends AppController{

    protected $auth_user = '';
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->sessionChecker(false);
        if(!empty($this->auth_user)){
            $this->set('auth_user',$this->auth_user);
        }
    }
    protected function sessionChecker($redirect = true){
        $session = $this->request->getSession();
        $session_id = $session->read('session_id');
        if(empty($session_id)){
            if($redirect){
                return $this->redirect('/login');
            }
            return false;

        }
        //check token
        $token_response = Utility::checkToken($session_id);
        if(!Utility::isSuccessResponse($token_response)){
            $session->delete('session_id');
            if($redirect){
                return $this->redirect('/login');
            }
            return false;
        }
        $this->auth_user = $token_response['data'];
        return true;
    }
}
